### ISSUE TITLE
How do you determine the number of sections for CARFAC

### ISSUE THREAD

**Issue by Kevinpsk** [vschaik/CARFAC#1]
Hi there, 

It is really nice to see you create a python version of CARFAC model. I was wondering when you set the number of sections to 100,  do you also change to gain provided by each section as well? My experience is each section provides a rather constant amount of gain, so if we increase the number of sections, it would also increase the cumulative gain at positions along the cochlea.  So I was wondering if you have done some special considerations for this effect or you just follow Lyon's parameter settings and just choose the number of section differently? 

Cheers and looking forward to your reply. 
Shuokai Pan

**Comment by vschaik** [comment]
You are correct that the number of sections changes the accumulated gain. I have not made any changes to the parameters to compensate. The notebooks are for illustration, and some of the other parameters might be different to Dick Lyon's default model. You will want to check against the parameters in CARFAC_Design.m available from [his repository](https://github.com/google/carfac/tree/master/matlab).
