### ISSUE TITLE
W1old never updated from zero

### ISSUE THREAD

**Issue by ddahlbom** [vschaik/CARFAC#2]
Forgive me if I am missing something obvious, but it appears that `W1old` is never updated from its initial state as a zero vector.  Given this, 

`v_OHC = W1 - W1old`

is always just equal to the current `W1`.  (This only applies to the CARFAC and CARFACAGC versions, as `W1old` is never used in the simple CAR model.)

**Comment by vschaik** [comment]
You're correct, thank you for spotting this. This should be changed to:
    v_OHC = W1 - W1old
    W1old = 1.0*W1

(The *1.0 is just to copy the array rather than assign it. You could use W1old = W1.copy() instead).

I'll fix it and push to GitHub when I get a moment.
